INSERT INTO test VALUES();
INSERT INTO students VALUES();
INSERT INTO student_test_participation VALUES();
INSERT INTO course VALUES();
INSERT INTO teacher VALUES();
INSERT INTO course_teacher VALUES();
INSERT INTO semester VALUES();
INSERT INTO grade VALUES();
INSERT INTO course_semester VALUES();
